name: Create Cypress report
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: Install a project with a clean slate
      run: |
        npm ci
        $(npm bin)/cypress cache path
        $(npm bin)/cypress cache list
        $(npm bin)/cypress verify

    - name: Run Cypress tests
      run: npm run integration
      continue-on-error: true

    - name: Merge test results into one
      run: npm run merge-reports

    - name: Generate HTML report
      run: npm run html-report

    - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
